micronaut:
  application:
    name: lotty
  server:
    port: 10000

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  security:
    authentication: cookie
    endpoints:
      logout:
        get-allowed: true
    oauth2:
      openid:
        additional-claims:
          access-token: true
      clients:
        github:
          client-id: da256483085163a28ebd
          scopes:
            - read:user
            - user:email
          authorization:
            url: https://github.com/login/oauth/authorize
          token:
            url: https://github.com/login/oauth/access_token
            auth-method: client-secret-post

        google:
          client-id: 122046305528-v2ibjb8juu3bb03sigie34cvikbhk65m.apps.googleusercontent.com
          openid:
            issuer: 'https://accounts.google.com'

  http:
    services:
      github-api:
        url: https://api.github.com

endpoints:
  env:
    enabled: true

datasources:
  default:
    url: jdbc:postgresql://${lotty.database.host}:5432/${lotty.database.name}
    username: ${lotty.database.user}
    password: ${lotty.database.password}
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    properties:
      hibernate:
        physical-naming-strategy: dev.myrold.domain.util.LottyNamingStrategy
        logical-naming-strategy:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:dev.myrold.db.migrations
      default-schema: lotty
      schemas:
        - lotty

netty:
  default:
    allocator:
      max-order: 3
